(()=>{'use strict';
const KB=JSON.parse(document.getElementById('kb-data').textContent), modules=KB.modules, byId=new Map(modules.map(m=>[m.id,m]));
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses=['未学','学习中','需复习','已掌握'], key='math-learning-library-v1', main=$('main');
const searchText=new Map(modules.map(m=>[m.id,JSON.stringify(m).toLocaleLowerCase()]));
let progress={}, view='home', timer;
function cleanProgress(saved){const out={};if(saved&&typeof saved==='object'&&!Array.isArray(saved)){for(const m of modules){const p=saved[m.id];if(p&&statuses.includes(p.status))out[m.id]={status:p.status,note:typeof p.note==='string'?p.note.slice(0,10000):'',updatedAt:typeof p.updatedAt==='string'?p.updatedAt:''};}}return out;}
try{progress=cleanProgress(JSON.parse(localStorage.getItem(key)||'{}'));}catch(e){$('save-warning').hidden=false;}
const state=id=>progress[id]?.status||'未学';
const save=(id,changes)=>{const stamp=new Date().toISOString();if(id)progress[id]={status:'未学',note:'',...(progress[id]||{}),...changes,updatedAt:stamp};try{if(id){const latest=cleanProgress(JSON.parse(localStorage.getItem(key)||'{}'));progress={...latest,[id]:{status:'未学',note:'',...(latest[id]||{}),...changes,updatedAt:stamp}};}localStorage.setItem(key,JSON.stringify(progress));$('save-warning').hidden=true;return true;}catch(e){$('save-warning').hidden=false;return false;}};
const toast=t=>{$('toast').textContent=t;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,4200);};
const list=items=>'<ul>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const ordered=items=>'<ol>'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol>';
const link=id=>byId.has(id)?'<a class="chip" href="#'+id+'" title="'+esc(byId.get(id).title)+'">'+esc(id)+' '+esc(byId.get(id).title)+'</a>':esc(id);
const shortLink=id=>'<a class="chip" href="#'+id+'" title="'+esc(byId.get(id)?.title)+'">'+esc(id)+'</a>';
const sourceLink=s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+'</a>';
const stageCounts=stage=>modules.filter(m=>m.stage===stage).length;
function renderList(){const q=$('search').value.trim().toLocaleLowerCase(),stage=$('stage').value,filter=$('state').value;
const found=modules.filter(m=>(!q||searchText.get(m.id).includes(q))&&(!stage||m.stage===stage)&&(!filter||state(m.id)===filter));
$('list-count').textContent=found.length+' / '+modules.length+' 个模块';
$('list').innerHTML=found.length?found.map(m=>'<button class="item '+(view===m.id?'selected':'')+'" data-id="'+m.id+'" aria-label="'+esc(m.id+' '+m.title+'，'+state(m.id))+'"'+(view===m.id?' aria-current="page"':'')+'><span class="id">'+m.id+'</span><span>'+esc(m.title)+'</span><span class="dot '+({'已掌握':'mastered','需复习':'review','学习中':'learning'}[state(m.id)]||'')+'" title="'+state(m.id)+'"></span></button>').join(''):'<p class="empty">未找到匹配内容。可换一个词，或清除筛选。</p>';}
function nextModule(){return KB.order.map(id=>byId.get(id)).find(m=>state(m.id)!=='已掌握'&&m.prerequisites.every(id=>state(id)==='已掌握'))||modules.find(m=>state(m.id)!=='已掌握')||modules[0];}
function homeBase(){const done=modules.filter(m=>state(m.id)==='已掌握').length,review=modules.filter(m=>state(m.id)==='需复习').length,learning=modules.filter(m=>state(m.id)==='学习中').length,next=nextModule();
main.innerHTML='<section class="hero"><p class="eyebrow">先理解，再推导，最后独立完成</p><h1>把零散知识，连成一条学习路径。</h1><p class="lead">从初中运算到高中综合，再到高阶公式。每一张知识卡都告诉你：先学什么、条件是什么、为什么成立，以及怎样检验自己是否真正理解。</p><div class="hero-actions"><button class="primary" data-go="'+next.id+'">'+(done||learning||review?'学习推荐：':'从基础开始：')+next.id+'</button><button data-go="routes">查看学习路线</button></div></section><div class="stats">'+['初中','高中','高阶拓展'].map(stage=>'<div class="stat"><strong>'+stageCounts(stage)+'</strong><span>'+stage+' · 个知识模块</span></div>').join('')+'</div><section class="progressbox"><div class="progressline"><strong>你的学习记录</strong><small>'+done+' / '+modules.length+' 已标记掌握</small></div><div class="track"><div class="fill" style="width:'+(done/modules.length*100)+'%"></div></div><p class="small muted">学习中 '+learning+' · 需复习 '+review+' · 状态由你自己记录，不是自动评分。</p></section><div class="cols"><section class="panel"><p class="eyebrow">每一张卡片</p><h2 style="margin-top:0">不只给公式，也讲条件</h2><p>前置知识与基础定义 → 方法与易错点 → 完整例题 → 遮住解析做自测。高阶卡另有正式定理、证明范围与推导。</p><p class="small muted">'+KB.stats.concepts+' 个细知识条目 · '+KB.stats.examples+' 道讲解例题 · '+KB.stats.practice+' 道自测</p></section><section class="panel"><p class="eyebrow">学习使用边界</p><h2 style="margin-top:0">主干版，而非穷尽版</h2><p>全国通用知识底座，尚未按地区设定考试权重。原创训练与真题证据分开，高阶拓展不标为统一高考必修。</p><p><a href="#sources">查看来源与版本核查</a></p></section></div><div class="notice">离线阅读可用。学习状态和个人笔记只存在当前浏览器；请定期点击“导出进度”备份。仓库副本不会自动同步学习进度。</div>';}
function home(){homeBase();main.insertAdjacentHTML('afterbegin','<div class="notice"><strong>v'+esc(KB.meta.version)+' 自学深化版</strong><p>'+KB.stats.deepStudyModules+' 个模块已补逐步自学讲解 · '+KB.stats.diagrams+' 幅数学图解 · '+KB.stats.layeredModules+' 个模块新增分层练习。<a href="#audit">查看审查结论与未完成事项</a></p><div class="links">'+modules.filter(m=>m.selfStudy).map(m=>shortLink(m.id)).join('')+'</div></div>');}
const steps=items=>'<div class="explain-steps">'+items.map((x,i)=>'<article><h3>'+String(i+1).padStart(2,'0')+' · '+esc(x.step)+'</h3><p>'+esc(x.detail)+'</p></article>').join('')+'</div>';
const checkBox=(title,c)=>'<section class="check-box"><h2>'+title+'</h2><p class="question">'+esc(c.question)+'</p><details><summary>先独立回答，再核对</summary><p><strong>答案：</strong>'+esc(c.answer)+'</p><p>'+esc(c.explanation)+'</p></details></section>';
function decorateModule(html,m){const s=m.selfStudy;
 const entry=s?'<p class="pill">已补详细自学讲解 · v1.1</p>'+checkBox('入门检查：我准备好了吗？',s.entryCheck):'<div class="notice">本模块当前为基础知识卡，尚未补齐详细自学讲解。先核对前置，再读例题；若无法解释其中一步，请记下卡点，不必急着标为掌握。</div>';
 const intuition=s?'<section class="intuition"><h2>直观入口：先看懂在研究什么</h2><p>'+esc(s.intuition)+'</p><p class="small muted">直观解释帮助形成想法；定理是否成立以条件和论证为准。</p></section>':'';
 html=html.replace('<section><h2>基础与概念</h2>',entry+intuition+'<section><h2>基础与概念</h2>');
 let detailed=s?'<section><h2>不跳步的推理</h2>'+steps(s.reasoning)+'</section>':'';
 if(m.illustrations)detailed+='<section><h2>图解与读图提示</h2>'+m.illustrations.map(d=>'<figure class="math-diagram">'+d.svg+'<figcaption>'+esc(d.caption)+'</figcaption></figure>').join('')+'</section>';
 const insertion=m.theorem?'<section class="theorem">':'<section><h2>解题方法</h2>';
 html=html.replace(insertion,detailed+insertion);
 if(s){html=html.replace('<section><h2>遮住解析，自己做</h2>','<section><h2>老师怎样想到并检查每一步</h2><p class="small muted">下面逐步拆解上方同一道例题；先自己说理由，再读对应解释。</p>'+steps(s.workedWalkthrough)+'</section><section class="wrong-example"><h2>错解对照：哪里看似合理却不成立？</h2><p><strong>错误说法：</strong>'+esc(s.wrongApproach.claim)+'</p><p><strong>错在哪里：</strong>'+esc(s.wrongApproach.whyWrong)+'</p><p><strong>怎样修正：</strong>'+esc(s.wrongApproach.correction)+'</p></section><section><h2>遮住解析，自己做</h2>');
 html=html.replace('<section><h2>掌握检查</h2>',checkBox('离开本节前：独立迁移',s.exitCheck)+'<section><h2>卡住时回哪里补</h2>'+s.remediation.map(r=>'<div class="remediation"><strong>'+esc(r.difficulty)+'</strong><p>'+link(r.moduleId)+'</p><p>'+esc(r.action)+'</p></div>').join('')+'</section><section><h2>掌握检查</h2>');}
 html=html.replace('两道自测是入门检查，不代表该专题的完整练习量。',m.practice.length>2?'先做基础，再做条件变式与综合应用。看解析前先写出理由；题量仍不代表专题已经穷尽。':'两道自测仅作入门检查，本模块的分层练习仍待扩充。');return html;}
function modulePage(m){const missing=m.prerequisites.filter(id=>state(id)!=='已掌握'), dependent=modules.filter(x=>x.prerequisites.includes(m.id));
let html='<p class="eyebrow">'+m.id+' / '+esc(m.stage)+' / '+esc(m.domain)+'</p><h1>'+esc(m.title)+'</h1><div class="meta"><span class="pill">'+esc(m.grade)+'</span>'+(m.courseType?'<span class="pill">'+esc(m.courseType)+'</span>':'')+'</div><div class="studybar"><label>学习状态 <select id="current-status" aria-label="当前模块学习状态">'+statuses.map(s=>'<option'+(s===state(m.id)?' selected':'')+'>'+s+'</option>').join('')+'</select></label><span class="small muted">先独立做题，再决定是否掌握</span></div><section><h2>先备知识</h2><div class="links">'+(m.prerequisites.length?m.prerequisites.map(link).join(''):'<span class="muted">本库起点，无必须先读的知识卡。</span>')+'</div>'+(missing.length?'<p class="small muted">以上有 '+missing.length+' 个前置尚未标记掌握；已有基础可直接阅读，需要时再补。</p>':'')+'</section><section><h2>本节要做到</h2>'+list(m.goals)+'</section><section><h2>基础与概念</h2>'+m.concepts.map((c,i)=>'<div class="concept"><h3><span class="concept-num">'+String(i+1).padStart(2,'0')+'</span>'+esc(c.name)+'</h3><p>'+esc(c.explanation)+'</p></div>').join('')+'</section>';
if(m.theorem){const t=m.theorem;html+='<section class="theorem"><p class="eyebrow">定理 / 条件 / 证明</p><h2>'+esc(t.name)+'</h2><h3>成立条件</h3>'+list(t.assumptions)+'<h3>结论</h3><div class="formula">'+esc(t.statement)+'</div><h3>为什么成立</h3><p class="proof-label">'+esc(t.proofLevel)+'</p>'+ordered(t.proof)+'</section>';}
if(m.derivation)html+='<section><h2>公式如何衍生</h2>'+ordered(m.derivation)+'</section>';
html+='<section><h2>解题方法</h2>'+list(m.methods)+'</section><div class="notice"><strong>易错与限制</strong>'+list(m.pitfalls)+'</div><section class="worked"><p class="eyebrow">原创编写 / 完整例题</p><h2>跟着推一次</h2><p class="question">'+esc(m.example.question.replace('【原创】',''))+'</p>'+ordered(m.example.solution)+'<p class="answer">答案：'+esc(m.example.answer)+'</p></section><section><h2>遮住解析，自己做</h2><p class="small muted">两道自测是入门检查，不代表该专题的完整练习量。</p>'+m.practice.map((p,i)=>'<article class="practice"><span class="pill">'+esc(p.level)+'</span><p class="question">'+(i+1)+'. '+esc(p.question.replace('【原创】',''))+'</p><details><summary>展开答案与解析</summary><p><strong>答案：</strong>'+esc(p.answer)+'</p><p><strong>解析：</strong>'+esc(p.solution)+'</p></details></article>').join('')+'</section><section><h2>掌握检查</h2>'+list(m.mastery)+'</section><section><h2>我的笔记与错因</h2><label><span class="sr-only">当前模块笔记</span><textarea aria-label="当前模块笔记" id="note" class="notearea" maxlength="10000" placeholder="记下卡住的一步、遗漏的条件，或自己找到的另一种证明…">'+esc(progress[m.id]?.note||'')+'</textarea></label><p id="note-status" class="small muted">仅保存在当前浏览器；最多 10000 字符，可随进度一起导出。</p></section>';
if(dependent.length)html+='<section><h2>学完可以接到</h2><div class="links">'+dependent.map(x=>link(x.id)).join('')+'</div></section>';
html+='<section class="sources"><h3>核查来源与对应范围</h3><ul>'+m.sources.map(s=>'<li>'+sourceLink(s)+'<br>'+esc(s.locator)+'</li>').join('')+'</ul><p>本卡为自行组织的讲解和训练，不是教材原文的逐字摘录。引用来源不代表逐页核完该教材。</p></section>';
const at=KB.order.indexOf(m.id),prev=byId.get(KB.order[at-1]),next=byId.get(KB.order[at+1]);html+='<div class="bottom-nav">'+(prev?'<button data-go="'+prev.id+'">← '+prev.id+' 上一模块</button>':'<span></span>')+'<button data-go="home">返回概览</button>'+(next?'<button data-go="'+next.id+'">下一模块 '+next.id+' →</button>':'<span></span>')+'</div>';main.innerHTML=decorateModule(html,m);
$('current-status').addEventListener('change',e=>{const ok=save(m.id,{status:e.target.value});renderList();toast(ok?'已保存 '+m.id+' 的学习状态':'暂未写入浏览器，请导出备份');});
$('note').addEventListener('input',e=>{$('note-status').textContent=save(m.id,{note:e.target.value})?'已保存到当前浏览器；请定期导出进度备份。':'本地保存失败，请导出进度备份。';});}
function routes(){main.innerHTML='<p class="eyebrow">知识之间的连接</p><h1>按依赖学习，不必按页码跳转。</h1><p class="lead">下列是主题主线，不是单一强制顺序。每张卡还列出跨分支前置；“上一／下一模块”按无环依赖排序安排。</p>'+KB.meta.routes.map(r=>'<section class="route"><h2>'+esc(r.title)+'</h2><p>'+esc(r.description)+'</p><div class="chain">'+r.ids.map(shortLink).join('<span class="arrow">→</span>')+'</div></section>').join('')+'<div class="notice">先确保中学主干稳固，再选择高阶分支。能用简单方法完成的题目，不要求强行使用高阶定理。</div>';}
function render(){const id=location.hash.slice(1)||'home';view=byId.has(id)||['home','routes','sources','exams','help','audit'].includes(id)?id:'home';
document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
if(byId.has(view)){modulePage(byId.get(view));document.title=view+' '+byId.get(view).title+' · 数学知识库';}else if(view==='home'){home();document.title='初高中数学自学知识库';}else if(view==='routes'){routes();document.title='学习路线 · 数学知识库';}else{main.innerHTML='<article class="doc">'+KB.docs[view]+'</article>';document.title=({'sources':'来源','exams':'真题证据','help':'使用说明','audit':'严谨性与自学审查'}[view])+' · 数学知识库';}
renderList();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-id],[data-go],[data-view]');if(b){location.hash=b.dataset.id||b.dataset.go||b.dataset.view;}});
window.addEventListener('storage',e=>{if(e.key!==key)return;try{progress=cleanProgress(JSON.parse(e.newValue||'{}'));renderList();if(view==='home')home();else if(byId.has(view)){const box=$('note');$('current-status').value=state(view);if(box&&document.activeElement!==box)box.value=progress[view]?.note||'';}}catch(error){toast('另一标签页的进度格式异常，请保留当前备份。');}});
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'auto'});});
['search','stage','state'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderList));
$('clear').addEventListener('click',()=>{['search','stage','state'].forEach(id=>$(id).value='');renderList();});
$('export').addEventListener('click',()=>{const data={format:'math-learning-library-progress',version:1,exportedAt:new Date().toISOString(),progress};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='数学学习进度_'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('进度文件已交给浏览器下载，请保留备份。');});
$('import').addEventListener('click',()=>$('import-file').click());
$('import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('文件超过 5 MB。');const data=JSON.parse(await file.text());if(data.format!=='math-learning-library-progress'||data.version!==1||!data.progress||Array.isArray(data.progress)||typeof data.progress!=='object')throw Error('不是本知识库导出的进度文件。');const next={};let count=0;for(const [id,p] of Object.entries(data.progress)){if(!byId.has(id))continue;if(!p||!statuses.includes(p.status)||typeof(p.note??'')!=='string')throw Error('进度字段不合法：'+id);next[id]={status:p.status,note:(p.note||'').slice(0,10000),updatedAt:typeof p.updatedAt==='string'?p.updatedAt:''};count++;}if(confirm('即将用 '+count+' 条记录覆盖本浏览器中这份知识库的全部进度和笔记。建议先导出备份。确定继续吗？')){progress=next;const ok=save();render();toast(ok?'已导入 '+count+' 条学习记录。':'已读入当前页，但浏览器保存失败，请导出备份。');}}catch(error){toast('导入失败：'+error.message);}finally{e.target.value='';}});
render();
})();
